# Hint: whenever you use a "rename-from" parameter in labelmaker, add a
# "on-rename-clash = 'error'" setting alongside it, so that we get an explicit
# signal that manual intervention is needed. That beause:
# - labelmaker does not support merging: https://github.com/jwodder/labelmaker/issues/8
# - the CLI does not accept a global --on-rename-clash parameter: https://github.com/jwodder/labelmaker/issues/126

# Default labels for all repositories.
[profiles.default]
on-rename-clash = 'error'

[[profiles.default.labels]]
name = "ğŸ› bug"
color = "FDC705"
description = "Something isn't working, or a fix is proposed"

[[profiles.default.labels]]
name = "ğŸ² can't reproduce"
color = "cfd3d7"
description = "Root cause not from project"

[[profiles.default.labels]]
name = "ğŸ†™ changelog"
color = "C2E0C6"
description = "Keep track of changes"

[[profiles.default.labels]]
name = "ğŸ¤– ci"
color = "A4A837"
description = "Continuous integration, tests, automation and management of the project"

[[profiles.default.labels]]
name = "ğŸ“¦ dependencies"
color = "AAA666"
description = "Dependencies changes"
rename-from = ["dependencies", "python:uv", "github-actions"]
on-rename-clash = 'error'

[[profiles.default.labels]]
name = "ğŸ“š documentation"
color = "006b75"
description = "Update to non-code (readme, docstrings, typos, â€¦)"

[[profiles.default.labels]]
name = "ğŸ§‘â€ğŸ¤â€ğŸ§‘ duplicate"
color = "cfd3d7"
description = "This issue or pull request already exists"

[[profiles.default.labels]]
name = "âœ¨ enhancement"
color = "1870E3"
description = "Improvement or change to an existing feature"

[[profiles.default.labels]]
name = "ğŸ feature request"
color = "84b6eb"
description = "Not existing yet and need to be implemented"

[[profiles.default.labels]]
name = "ğŸŒ± good first issue"
color = "B3CD7F"
description = "A place for newcomers to start contributing"

[[profiles.default.labels]]
name = "ğŸ™ help wanted"
color = "C2E0C6"
description = "I can't do this alone and need contributors"

[[profiles.default.labels]]
name = "â” question"
color = "d876e3"
description = "Further information is requested"

[[profiles.default.labels]]
name = "ğŸ’£ security"
color = "F83911"
description = "Exploit, token leaks, â€¦"

[[profiles.default.labels]]
name = "ğŸ’– sponsor"
color = "D3B3F2"
description = "A sponsor is involved"

[[profiles.default.labels]]
name = "ğŸš« wont do/fix"
color = "cfd3d7"
description = "This will not be worked on"

# Additional labels for awesome-* repositories.
[profiles.awesome]
on-rename-clash = 'error'

[[profiles.awesome.labels]]
name = "âš–ï¸ curation"
color = "d73a4a"
description = "Links or structure needs to be refined"

[[profiles.awesome.labels]]
name = "ğŸ†• new link"
color = "fbca04"
description = "A link worth adding to the list"

[[profiles.awesome.labels]]
name = "ğŸ©¹ fix link"
color = "d4c5f9"
description = "Existing link need to be updated"
