# ref: https://github.com/lycheeverse/lychee/blob/master/lychee.example.toml

# XXX One day we might move this config directly into pyproject.toml:
# https://github.com/lycheeverse/lychee/issues/1930

exclude = [
    # GitHub issue comment fragments are dynamically loaded and can't be verified.
    "^https://github.com/.+/issues/[0-9]+#issuecomment-.*$",
]
